CREATE DATABASE kanban
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


CREATE TABLE kanban
(
    id           INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL UNIQUE,
    CONSTRAINT kanban_pkey PRIMARY KEY (id)
);

CREATE TABLE columns
(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(40) NOT NULL,
	CONSTRAINT columns_pkey PRIMARY KEY (id)

);



CREATE TABLE kanban_column
(
    kanban_id integer,
    column_id integer,
    CONSTRAINT kanban_id_fkey FOREIGN KEY (kanban_id)
        REFERENCES kanban (id)
        ON DELETE no action
        ON UPDATE no action,
    CONSTRAINT column_id_fkey FOREIGN KEY (column_id)
        REFERENCES columns (id)
        ON DELETE no action
        ON UPDATE no action
);

CREATE TABLE rows
(
        id INT GENERATED BY DEFAULT AS IDENTITY,
        row_nm integer NOT NULL,
        kanban_id integer NOT NULL,
        CONSTRAINT rows_pkey PRIMARY KEY (id),
        CONSTRAINT kanban_id_fkey FOREIGN KEY (kanban_id)
        REFERENCES kanban (id)
        ON DELETE no action
        ON UPDATE no action
);

CREATE TABLE column_data
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    column_id integer NOT NULL,
    data varchar(100),
    CONSTRAINT column_data_pkey PRIMARY KEY (id),
    CONSTRAINT column_id_fkey FOREIGN KEY (column_id)
    REFERENCES columns(id)
    ON DELETE no action
    ON UPDATE no action
);

CREATE TABLE column_data_row
(
    row_id integer,
    column_data_id integer,
    CONSTRAINT row_id_fkey FOREIGN KEY (row_id)
        REFERENCES rows (id)
        ON DELETE no action
        ON UPDATE no action,
    CONSTRAINT column_data_id_fkey FOREIGN KEY (column_data_id)
        REFERENCES column_data (id)
        ON DELETE no action
        ON UPDATE no action
);
